/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Microsoft.Presidio.Client;
using Microsoft.Presidio.Model;

namespace Microsoft.Presidio.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IDeanonymizeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>DeanonymizeResponse</returns>
        DeanonymizeResponse DeanonymizePost (DeanonymizeRequest body);

        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of DeanonymizeResponse</returns>
        ApiResponse<DeanonymizeResponse> DeanonymizePostWithHttpInfo (DeanonymizeRequest body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of DeanonymizeResponse</returns>
        System.Threading.Tasks.Task<DeanonymizeResponse> DeanonymizePostAsync (DeanonymizeRequest body);

        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (DeanonymizeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeanonymizeResponse>> DeanonymizePostAsyncWithHttpInfo (DeanonymizeRequest body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class DeanonymizeApi : IDeanonymizeApi
    {
        private Microsoft.Presidio.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DeanonymizeApi(String basePath)
        {
            this.Configuration = new Microsoft.Presidio.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Microsoft.Presidio.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class
        /// </summary>
        /// <returns></returns>
        public DeanonymizeApi()
        {
            this.Configuration = Microsoft.Presidio.Client.Configuration.Default;

            ExceptionFactory = Microsoft.Presidio.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DeanonymizeApi(Microsoft.Presidio.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Microsoft.Presidio.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Microsoft.Presidio.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Microsoft.Presidio.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Microsoft.Presidio.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>DeanonymizeResponse</returns>
        public DeanonymizeResponse DeanonymizePost (DeanonymizeRequest body)
        {
             ApiResponse<DeanonymizeResponse> localVarResponse = DeanonymizePostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of DeanonymizeResponse</returns>
        public ApiResponse< DeanonymizeResponse > DeanonymizePostWithHttpInfo (DeanonymizeRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DeanonymizeApi->DeanonymizePost");

            var localVarPath = "/deanonymize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeanonymizePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeanonymizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DeanonymizeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeanonymizeResponse)));
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of DeanonymizeResponse</returns>
        public async System.Threading.Tasks.Task<DeanonymizeResponse> DeanonymizePostAsync (DeanonymizeRequest body)
        {
             ApiResponse<DeanonymizeResponse> localVarResponse = await DeanonymizePostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (DeanonymizeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DeanonymizeResponse>> DeanonymizePostAsyncWithHttpInfo (DeanonymizeRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DeanonymizeApi->DeanonymizePost");

            var localVarPath = "/deanonymize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeanonymizePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DeanonymizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (DeanonymizeResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DeanonymizeResponse)));
        }

    }
}
