:: Generated by: https://github.com/swagger-api/swagger-codegen.git
::

@echo off

dotnet restore src\Microsoft.Presidio
dotnet build src\Microsoft.Presidio
echo Now, run the following to start the project: dotnet run -p src\Microsoft.Presidio\Microsoft.Presidio.csproj --launch-profile web.
echo.
