/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Models
{ 
    /// <summary>
    /// Replace with hashed value
    /// </summary>
    [DataContract]
    public partial class Hash : IEquatable<Hash>
    { 
        /// <summary>
        /// hash
        /// </summary>
        /// <value>hash</value>
        [Required]
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// The hashing algorithm
        /// </summary>
        /// <value>The hashing algorithm</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum HashTypeEnum
        {
            /// <summary>
            /// Enum Md5Enum for md5
            /// </summary>
            [EnumMember(Value = "md5")]
            Md5Enum = 0,
            /// <summary>
            /// Enum Sha256Enum for sha256
            /// </summary>
            [EnumMember(Value = "sha256")]
            Sha256Enum = 1,
            /// <summary>
            /// Enum Sha512Enum for sha512
            /// </summary>
            [EnumMember(Value = "sha512")]
            Sha512Enum = 2        }

        /// <summary>
        /// The hashing algorithm
        /// </summary>
        /// <value>The hashing algorithm</value>
        [DataMember(Name="hash_type")]
        public HashTypeEnum? HashType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Hash {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  HashType: ").Append(HashType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Hash)obj);
        }

        /// <summary>
        /// Returns true if Hash instances are equal
        /// </summary>
        /// <param name="other">Instance of Hash to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Hash other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    HashType == other.HashType ||
                    HashType != null &&
                    HashType.Equals(other.HashType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (HashType != null)
                    hashCode = hashCode * 59 + HashType.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Hash left, Hash right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Hash left, Hash right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
