/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RecognizerResultWithAnaysisExplanation : RecognizerResult, IEquatable<RecognizerResultWithAnaysisExplanation>
    { 
        /// <summary>
        /// Gets or Sets AnalysisExplanation
        /// </summary>
        [DataMember(Name="analysis_explanation")]
        public AnalysisExplanation AnalysisExplanation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecognizerResultWithAnaysisExplanation {\n");
            sb.Append("  AnalysisExplanation: ").Append(AnalysisExplanation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RecognizerResultWithAnaysisExplanation)obj);
        }

        /// <summary>
        /// Returns true if RecognizerResultWithAnaysisExplanation instances are equal
        /// </summary>
        /// <param name="other">Instance of RecognizerResultWithAnaysisExplanation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecognizerResultWithAnaysisExplanation other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AnalysisExplanation == other.AnalysisExplanation ||
                    AnalysisExplanation != null &&
                    AnalysisExplanation.Equals(other.AnalysisExplanation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AnalysisExplanation != null)
                    hashCode = hashCode * 59 + AnalysisExplanation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RecognizerResultWithAnaysisExplanation left, RecognizerResultWithAnaysisExplanation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RecognizerResultWithAnaysisExplanation left, RecognizerResultWithAnaysisExplanation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
