/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnalysisExplanation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalysisExplanationTests
    {
        // TODO uncomment below to declare an instance variable for AnalysisExplanation
        //private AnalysisExplanation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnalysisExplanation
            //instance = new AnalysisExplanation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnalysisExplanation
        /// </summary>
        [Test]
        public void AnalysisExplanationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnalysisExplanation
            //Assert.IsInstanceOfType<AnalysisExplanation> (instance, "variable 'instance' is a AnalysisExplanation");
        }


        /// <summary>
        /// Test the property 'Recognizer'
        /// </summary>
        [Test]
        public void RecognizerTest()
        {
            // TODO unit test for the property 'Recognizer'
        }
        /// <summary>
        /// Test the property 'PatternName'
        /// </summary>
        [Test]
        public void PatternNameTest()
        {
            // TODO unit test for the property 'PatternName'
        }
        /// <summary>
        /// Test the property 'Pattern'
        /// </summary>
        [Test]
        public void PatternTest()
        {
            // TODO unit test for the property 'Pattern'
        }
        /// <summary>
        /// Test the property 'OriginalScore'
        /// </summary>
        [Test]
        public void OriginalScoreTest()
        {
            // TODO unit test for the property 'OriginalScore'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'TextualExplanation'
        /// </summary>
        [Test]
        public void TextualExplanationTest()
        {
            // TODO unit test for the property 'TextualExplanation'
        }
        /// <summary>
        /// Test the property 'ScoreContextImprovement'
        /// </summary>
        [Test]
        public void ScoreContextImprovementTest()
        {
            // TODO unit test for the property 'ScoreContextImprovement'
        }
        /// <summary>
        /// Test the property 'SupportiveContextWord'
        /// </summary>
        [Test]
        public void SupportiveContextWordTest()
        {
            // TODO unit test for the property 'SupportiveContextWord'
        }
        /// <summary>
        /// Test the property 'ValidationResult'
        /// </summary>
        [Test]
        public void ValidationResultTest()
        {
            // TODO unit test for the property 'ValidationResult'
        }

    }

}
