/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnyOfAnonymizeRequestAnonymizers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnyOfAnonymizeRequestAnonymizersTests
    {
        // TODO uncomment below to declare an instance variable for AnyOfAnonymizeRequestAnonymizers
        //private AnyOfAnonymizeRequestAnonymizers instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnyOfAnonymizeRequestAnonymizers
            //instance = new AnyOfAnonymizeRequestAnonymizers();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnyOfAnonymizeRequestAnonymizers
        /// </summary>
        [Test]
        public void AnyOfAnonymizeRequestAnonymizersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnyOfAnonymizeRequestAnonymizers
            //Assert.IsInstanceOfType<AnyOfAnonymizeRequestAnonymizers> (instance, "variable 'instance' is a AnyOfAnonymizeRequestAnonymizers");
        }



    }

}
