/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Mask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MaskTests
    {
        // TODO uncomment below to declare an instance variable for Mask
        //private Mask instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Mask
            //instance = new Mask();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Mask
        /// </summary>
        [Test]
        public void MaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Mask
            //Assert.IsInstanceOfType<Mask> (instance, "variable 'instance' is a Mask");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'MaskingChar'
        /// </summary>
        [Test]
        public void MaskingCharTest()
        {
            // TODO unit test for the property 'MaskingChar'
        }
        /// <summary>
        /// Test the property 'CharsToMask'
        /// </summary>
        [Test]
        public void CharsToMaskTest()
        {
            // TODO unit test for the property 'CharsToMask'
        }
        /// <summary>
        /// Test the property 'FromEnd'
        /// </summary>
        [Test]
        public void FromEndTest()
        {
            // TODO unit test for the property 'FromEnd'
        }

    }

}
