/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RecognizerResultWithAnaysisExplanation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecognizerResultWithAnaysisExplanationTests
    {
        // TODO uncomment below to declare an instance variable for RecognizerResultWithAnaysisExplanation
        //private RecognizerResultWithAnaysisExplanation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecognizerResultWithAnaysisExplanation
            //instance = new RecognizerResultWithAnaysisExplanation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecognizerResultWithAnaysisExplanation
        /// </summary>
        [Test]
        public void RecognizerResultWithAnaysisExplanationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecognizerResultWithAnaysisExplanation
            //Assert.IsInstanceOfType<RecognizerResultWithAnaysisExplanation> (instance, "variable 'instance' is a RecognizerResultWithAnaysisExplanation");
        }


        /// <summary>
        /// Test the property 'AnalysisExplanation'
        /// </summary>
        [Test]
        public void AnalysisExplanationTest()
        {
            // TODO unit test for the property 'AnalysisExplanation'
        }

    }

}
