/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Microsoft.Presidio.Client.SwaggerDateConverter;

namespace Microsoft.Presidio.Model
{
    /// <summary>
    /// Replace with a given value
    /// </summary>
    [DataContract]
        public partial class Replace :  IEquatable<Replace>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Replace" /> class.
        /// </summary>
        /// <param name="type">replace (required).</param>
        /// <param name="newValue">The string to replace with (required).</param>
        public Replace(string type = default(string), string newValue = default(string))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for Replace and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "newValue" is required (not null)
            if (newValue == null)
            {
                throw new InvalidDataException("newValue is a required property for Replace and cannot be null");
            }
            else
            {
                this.NewValue = newValue;
            }
        }
        
        /// <summary>
        /// replace
        /// </summary>
        /// <value>replace</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// The string to replace with
        /// </summary>
        /// <value>The string to replace with</value>
        [DataMember(Name="new_value", EmitDefaultValue=false)]
        public string NewValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Replace {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  NewValue: ").Append(NewValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Replace);
        }

        /// <summary>
        /// Returns true if Replace instances are equal
        /// </summary>
        /// <param name="input">Instance of Replace to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Replace input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.NewValue == input.NewValue ||
                    (this.NewValue != null &&
                    this.NewValue.Equals(input.NewValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.NewValue != null)
                    hashCode = hashCode * 59 + this.NewValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
