/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Microsoft.Presidio.Attributes;

using Microsoft.AspNetCore.Authorization;
using Microsoft.Presidio.Models;

namespace Microsoft.Presidio.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DeanonymizeApiController : ControllerBase
    { 
        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="422">Unprocessable Entity</response>
        [HttpPost]
        [Route("/deanonymize")]
        [ValidateModelState]
        [SwaggerOperation("DeanonymizePost")]
        [SwaggerResponse(statusCode: 200, type: typeof(DeanonymizeResponse), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Bad request")]
        [SwaggerResponse(statusCode: 422, type: typeof(InlineResponse422), description: "Unprocessable Entity")]
        public virtual IActionResult DeanonymizePost([FromBody]DeanonymizeRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(DeanonymizeResponse));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(InlineResponse400));

            //TODO: Uncomment the next line to return response 422 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(422, default(InlineResponse422));
            string exampleJson = null;
            exampleJson = "{\n  \"text\" : \"text\",\n  \"items\" : [ {\n    \"entity_type\" : \"entity_type\",\n    \"start\" : 0,\n    \"end\" : 6,\n    \"text\" : \"text\",\n    \"operator\" : \"operator\"\n  }, {\n    \"entity_type\" : \"entity_type\",\n    \"start\" : 0,\n    \"end\" : 6,\n    \"text\" : \"text\",\n    \"operator\" : \"operator\"\n  } ]\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<DeanonymizeResponse>(exampleJson)
                        : default(DeanonymizeResponse);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
