/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Presidio.Api;
using Microsoft.Presidio.Model;
using Microsoft.Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Test
{
    /// <summary>
    ///  Class for testing AnonymizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnonymizeRequestTests
    {
        // TODO uncomment below to declare an instance variable for AnonymizeRequest
        //private AnonymizeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnonymizeRequest
            //instance = new AnonymizeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnonymizeRequest
        /// </summary>
        [Test]
        public void AnonymizeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnonymizeRequest
            //Assert.IsInstanceOfType<AnonymizeRequest> (instance, "variable 'instance' is a AnonymizeRequest");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Anonymizers'
        /// </summary>
        [Test]
        public void AnonymizersTest()
        {
            // TODO unit test for the property 'Anonymizers'
        }
        /// <summary>
        /// Test the property 'AnalyzerResults'
        /// </summary>
        [Test]
        public void AnalyzerResultsTest()
        {
            // TODO unit test for the property 'AnalyzerResults'
        }

    }

}
