/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Presidio.Api;
using Microsoft.Presidio.Model;
using Microsoft.Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Test
{
    /// <summary>
    ///  Class for testing DeanonymizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeanonymizeRequestTests
    {
        // TODO uncomment below to declare an instance variable for DeanonymizeRequest
        //private DeanonymizeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeanonymizeRequest
            //instance = new DeanonymizeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeanonymizeRequest
        /// </summary>
        [Test]
        public void DeanonymizeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeanonymizeRequest
            //Assert.IsInstanceOfType<DeanonymizeRequest> (instance, "variable 'instance' is a DeanonymizeRequest");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Deanonymizers'
        /// </summary>
        [Test]
        public void DeanonymizersTest()
        {
            // TODO unit test for the property 'Deanonymizers'
        }
        /// <summary>
        /// Test the property 'AnonymizerResults'
        /// </summary>
        [Test]
        public void AnonymizerResultsTest()
        {
            // TODO unit test for the property 'AnonymizerResults'
        }

    }

}
