/* 
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * OpenAPI spec version: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Presidio.Api;
using Microsoft.Presidio.Model;
using Microsoft.Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Test
{
    /// <summary>
    ///  Class for testing DeanonymizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeanonymizeRequestTests
    {
        private DeanonymizeRequest instance;
        private Dictionary<string, object> deanonymizers;
        private List<AnonymizerResult> results;
        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            var decrypt = new Decrypt("decrypt", "3t6w9z$C&F)J@NcR");
            deanonymizers = new Dictionary<string, object>() {{"PERSON", decrypt}};
            var anonymizerResult = new AnonymizerResult(start: 11, end: 55, entityType: "PERSON");
            results = new List<AnonymizerResult>() {anonymizerResult};
            instance = new DeanonymizeRequest(text: "hello world", deanonymizers: deanonymizers, anonymizerResults: results);
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeanonymizeRequest
        /// </summary>
        [Test]
        public void DeanonymizeRequestInstanceTest()
        {
            Assert.IsInstanceOfType(typeof(DeanonymizeRequest),instance, "variable 'instance' is a DeanonymizeRequest");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            Assert.IsTrue(instance.Text == "hello world");
        }
        /// <summary>
        /// Test the property 'Deanonymizers'
        /// </summary>
        [Test]
        public void DeanonymizersTest()
        {
            Assert.IsTrue(instance.Deanonymizers == deanonymizers);
        }
        /// <summary>
        /// Test the property 'AnonymizerResults'
        /// </summary>
        [Test]
        public void AnonymizerResultsTest()
        {
            Assert.IsTrue(instance.AnonymizerResults == results);
        }

    }

}
